# Generated by Django 4.2.8 on 2024-01-16 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='to',
            name='maintenance_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MaintenanceCompanyTo', to='users.service'),
        ),
        migrations.AddField(
            model_name='to',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ServiceCompanyTo', to='users.service'),
        ),
        migrations.AddField(
            model_name='to',
            name='type_of_maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MaintenanceTo', to='service.typeto'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CarComplaints', to='service.cars'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='failure_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FailuresComplaints', to='service.failure'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='recovery_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RecoveryMethodsComplaints', to='service.recoverymethod'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ServiceCompanyComplaints', to='users.service'),
        ),
        migrations.AddField(
            model_name='cars',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClientCars', to='users.client'),
        ),
        migrations.AddField(
            model_name='cars',
            name='drive_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AxleCars', to='service.axle'),
        ),
        migrations.AddField(
            model_name='cars',
            name='engine_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EngineCars', to='service.engine'),
        ),
        migrations.AddField(
            model_name='cars',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ServiceCompanyCars', to='users.service'),
        ),
        migrations.AddField(
            model_name='cars',
            name='steering_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SteeringAxleCars', to='service.steeringaxle'),
        ),
        migrations.AddField(
            model_name='cars',
            name='transmission_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TransmissionCars', to='service.transmission'),
        ),
        migrations.AddField(
            model_name='cars',
            name='vehicle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TechniqueCars', to='service.technique'),
        ),
    ]
