services:
  react-app:
    build: ./frontend/sealant
    ports:
      - "3000:3000"
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django_network
    restart: always
  web:
    build: ./backend/sealant
    volumes:
      - ./backend/sealant:/app
    ports:
      - "8000:8080"
    environment:
      - DJANGO_SETTINGS_MODULE=sealant.settings
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - django_network
    command:
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py initadmin && python manage.py runserver 0.0.0.0:8080"
    restart: always

volumes:
  postgres_data:

networks:
  django_network:
